### ISSUE TITLE
Add pre-trained model

### ISSUE THREAD

**Issue by JRMeyer** [tabahi/Phoneme-Converge-SER#1]
Hi there @tabahi 👋 

It would be great to include a pre-trained model so users can test this out of the box:)

**Comment by tabahi** [comment]
Thanks for the suggestion. I have uploaded pre-trained models on Onedrive (495 MBs) and created a python package that you can use easily for prediction. 

[Pre-trained model](https://github.com/tabahi/Phoneme-Converge-SER#pre-trained-model)
